plugins {
    id 'io.micronaut.build.internal.tracing-module'
}

dependencies {
    api platform(libs.boms.opentelemetry)
    api platform(libs.boms.opentelemetry.alpha)
    api platform(libs.boms.opentelemetry.instrumentation)
    api platform(libs.boms.opentelemetry.instrumentation.alpha)
    api projects.micronautTracingOpentelemetry
    api libs.opentelemetry.api
    api libs.opentelemetry.instrumentation.r2dbc

    implementation libs.micronaut.r2dbc.core

    testImplementation libs.reactor.core
    testImplementation libs.opentelemetry.sdk
    testImplementation libs.opentelemetry.sdk.testing
    testRuntimeOnly libs.r2dbc.h2
}

micronautBuild {
    binaryCompatibility {
        enabled = false
    }
}
