This section will document breaking changes that may happen during milestone or release candidate releases, as well as major releases eg (1.x.x → 2.x.x).

== Micronaut Tracing 4.5.0 breaking changes

Micronaut Tracing `4.5.0` upgrades the OpenTelemetry annotation support to OpenTelemetry Instrumentation `1.19.0`.
That release moved `@WithSpan` and `@SpanAttribute` from `io.opentelemetry.extension.annotations` to `io.opentelemetry.instrumentation.annotations`.

If your application uses `micronaut-tracing-opentelemetry-annotation` and imports the old package, update those imports to the new package before upgrading to Micronaut Tracing `4.5.0` or newer.

If you upgrade to Micronaut Tracing `4.5.0` independently from the Micronaut Platform version used by your application, import the matching `io.micronaut.tracing:micronaut-tracing-bom` version (the same version as your Micronaut Tracing version) in dependency management.
Applications that keep an older Micronaut Platform-managed tracing BOM while forcing only the Micronaut Tracing OpenTelemetry module version can resolve incompatible OpenTelemetry instrumentation, semantic conventions, SDK, and exporter artifacts.

== Micronaut Tracing 5.0.0-M2 breaking changes

The Micronaut Tracing Zipkin module (`io.micronaut.tracing:micronaut-tracing-zipkin`) has been renamed and separated in two new modules:

- Micronaut Tracing Brave (`io.micronaut.tracing:micronaut-tracing-brave`)
- Micronaut Tracing Brave HTTP (`io.micronaut.tracing:micronaut-tracing-brave-http`)

if you are using OpenTracing and Micronaut Tracing Zipkin module, you have to change `io.micronaut.tracing:micronaut-tracing-zipkin` dependency to `io.micronaut.tracing:micronaut-tracing-brave-http`. The Micronaut Tracing Brave HTTP brings HTTP filters for auto instrumentation of your requests. If you don't need HTTP filters you can only add `io.micronaut.tracing:micronaut-tracing-brave` dependency.

== Micronaut Tracing 7.0.0 Breaking changes

The following dependencies have been updated:

- Open Telemetry 1.36
- Open Telemetry Instrumentation 1.33.1

The Open Telemetry updates required updating the following Zipkin dependencies to a new major version:

- Zipkin Reporter 3.3.0
- Zipkin Brave 6.0.2

The only change due to the above dependency updates that might affect end user code is that the `errorParser` property has been removed from `io.micronaut.tracing.brave.BraveTracerConfiguration` as the `brave.ErrorParser` type no longer exists.

The `io.micronaut.tracing.zipkin.http.client.HttpClientSender` class is now deprecated as it implements a deprecated Zipkin API. This class will be replaced with an implementation based on the Zipkin 3 APIs in a future release.

== Micronaut Tracing 8.4.0 behavior changes

With `micronaut-tracing-opentelemetry-http`, the requests to the Micronaut management endpoints (`/health`, `/info`, `/prometheus`...) are no longer traced by the HTTP server filter. Set `tracing.opentelemetry.http.server.exclude-management-endpoints` to `false` to trace them again, or list the ids of the endpoints to trace in `tracing.opentelemetry.http.server.traced-management-endpoints`. See <<performance, Performance Tuning>>.

== Micronaut Tracing 8.4.0 deprecations

The OpenTracing based modules are deprecated and will be removed in the next major version, since OpenTracing and the Jaeger client are archived:

* `micronaut-tracing-opentracing`
* `micronaut-tracing-jaeger`
* the OpenTracing `io.opentracing.Tracer` bean of `micronaut-tracing-brave`

A warning is logged once when an OpenTracing tracer is created. See <<migrationFromOpenTracing, Migrating from OpenTracing>> to move to OpenTelemetry or to Micrometer Tracing with Brave.

The OpenTracing HTTP filters can now set the `error` tag to the boolean `true` defined by the OpenTracing semantic conventions, and record the error message as a span log event, with `tracing.opentracing.boolean-error-tag: true`. By default the `error` tag still holds the error message.
