When operating Microservices in production it can be challenging to troubleshoot interactions between Microservices in a distributed architecture.

To solve this problem, a way to visualize interactions between Microservices in a distributed manner can be critical. Currently, there are various distributed tracing solutions, the most popular of which are https://zipkin.io/[Zipkin] and https://www.jaegertracing.io/[Jaeger], both of which provide different levels of support for the https://opentracing.io/[Open Tracing] API.

Micronaut features integration with both Zipkin and Jaeger (via the Open Tracing API).

== Tracing Annotations

The pkg:tracing.annotation[] package contains annotations for creating new spans, continuing existing spans, and adding span tags.
You can also declare ann:tracing.annotation.NewSpan[] on a class or interface to create a new span for each method invocation.

The available annotations are:

* The ann:tracing.annotation.NewSpan[] annotation creates a new span, wrapping the method call or reactive type. It can be declared on a method, class, or interface. Method-level annotations take precedence over class-level or interface-level annotations.
* The ann:tracing.annotation.ContinueSpan[] annotation continues an existing span, wrapping the method call or reactive type.
* The ann:tracing.annotation.SpanTag[] annotation can be used on method arguments to include the value of the argument within a Span's tags. When you use `@SpanTag` on an argument, you must either annotate the method with `@NewSpan` or `@ContinueSpan`.

The following snippet presents an example of using the annotations:

snippet::io.micronaut.tracing.docs.HelloService[project-base="test-suite", tags="imports,clazz", title="Using Trace Annotations"]

<1> The ann:tracing.annotation.NewSpan[] annotation starts a new span
<2> Use ann:tracing.annotation.SpanTag[] to include method arguments as tags for the span
<3> Use the ann:tracing.annotation.ContinueSpan[] annotation to continue an existing span and incorporate additional tags using `@SpanTag`

[.lang-python]
NOTE: In Python, a method invoked on `self` from within the same bean (`self.greet(...)` in `hello`) does not go through the bean's interceptors, so the `@ContinueSpan` tags of `greet` are only recorded when `greet` is invoked from another bean while a span is active.

=== Tracing Instrumentation

In addition to explicit tracing tags, Micronaut includes a number of instrumentations to ensure that the Span context is propagated between threads and across Microservice boundaries.

These instrumentations are found in the `io.micronaut.tracing.instrument` package and include https://docs.micronaut.io/latest/guide/#clientFilter[Client Filters] and https://docs.micronaut.io/latest/guide/#filters[Server Filters] to propagate the necessary headers via HTTP.

== Tracing Beans

If the Tracing annotations and existing instrumentations are not sufficient, Micronaut's tracing integration registers a `io.opentracing.Tracer` bean which exposes the Open Tracing API and can be dependency-injected as needed.

Depending on the implementation you choose, there are also additional beans. For example for Zipkin `brave.Tracing` and `brave.SpanCustomizer` beans are available too.
