plugins {
    id 'io.micronaut.build.internal.tracing-base'
    id 'io.micronaut.build.internal.module'
    id("org.sonatype.gradle.plugins.scan")
}
String ossIndexUsername = System.getenv("OSS_INDEX_USERNAME") ?: project.properties["ossIndexUsername"]
String ossIndexPassword = System.getenv("OSS_INDEX_PASSWORD") ?: project.properties["ossIndexPassword"]
boolean sonatypePluginConfigured = ossIndexUsername != null && ossIndexPassword != null
ossIndexAudit {
if (sonatypePluginConfigured) {
    username = ossIndexUsername
    password = ossIndexPassword
}
    excludeCoordinates = [
        "com.squareup.okio:okio:2.8.0", // no okio 2.x version patched
    ]
}
dependencies {
    annotationProcessor mn.micronaut.inject.java
    annotationProcessor libs.micronaut.docs.asciidoc.config.props

    testAnnotationProcessor mn.micronaut.inject.java
    testImplementation mn.micronaut.inject.groovy
    testImplementation mn.micronaut.inject.java
    testImplementation mn.micronaut.http.server.netty
}

tasks.withType(Test) {
    testLogging {
        showStandardStreams = true
        exceptionFormat = 'full'
    }
}
