plugins {
    id 'io.micronaut.build.internal.tracing-base'
    id 'io.micronaut.build.internal.module'
}
ossIndexAudit {
    excludeCoordinates = [
        "com.squareup.okio:okio:2.8.0", // no okio 2.x version patched
        "com.squareup.okio:okio:2.10.0", // no okio 2.x version patched
        "org.lz4:lz4-java:1.8.1", // CVE-2025-12183
        "org.lz4:lz4-java:1.8.1" // CVE-2025-12183
    ]
}
dependencies {
    annotationProcessor mn.micronaut.inject.java
    annotationProcessor libs.micronaut.docs.asciidoc.config.props

    testAnnotationProcessor mn.micronaut.inject.java
    testImplementation mn.micronaut.inject.groovy
    testImplementation mn.micronaut.inject.java
    testImplementation mn.micronaut.http.server.netty
}

tasks.withType(Test) {
    testLogging {
        showStandardStreams = true
        exceptionFormat = 'full'
    }
}
