plugins {
    alias libs.plugins.kotlinjvm
    alias libs.plugins.kotlinkapt
    id "io.micronaut.build.internal.kotlin-base"
}

dependencies {
    annotationProcessor(mnSerde.micronaut.serde.processor)

    api projects.micronautTracingCore
    api mn.micronaut.http.client
    api mn.micronaut.core.processor

    api mn.kotlinx.coroutines.core
    api mn.kotlinx.coroutines.reactor

    kaptTest mn.micronaut.inject.java

    testImplementation mn.kotlinx.coroutines.core
    testImplementation mn.kotlinx.coroutines.reactor

    testImplementation mn.micronaut.http.server.netty
    testImplementation mnTest.micronaut.test.junit5
    testImplementation mnTest.junit.jupiter.engine
    testImplementation mnSerde.micronaut.serde.jackson
    testRuntimeOnly(mnTest.junit.platform.launcher)
    testRuntimeOnly(mnTest.junit.jupiter.engine)
}

tasks.withType(Test).configureEach {
    useJUnitPlatform()
}
