plugins {
    id 'io.micronaut.build.internal.tracing-module'
    id 'io.micronaut.build.internal.kotlin'
}

dependencies {
    api libs.opentracing
    api libs.opentracing.util
    api projects.micronautTracingCore
    api mnReactor.micronaut.reactor

    testImplementation mnReactor.micronaut.reactor
    testImplementation "io.reactivex.rxjava3:rxjava"
    testImplementation mnRxjava3.micronaut.rxjava3.http.client
    testImplementation mnReactor.micronaut.reactor.http.client
    testImplementation project(":micronaut-tracing-jaeger")
    testRuntimeOnly mnSerde.micronaut.serde.jackson
}
