plugins {
    id 'io.micronaut.build.internal.tracing-module'
}

dependencies {
    api mn.micronaut.http.client
    api projects.micronautTracingAnnotation

    testImplementation mnReactor.micronaut.reactor
    testImplementation "io.reactivex.rxjava3:rxjava"
    testImplementation mnRxjava3.micronaut.rxjava3.http.client
    testImplementation mnReactor.micronaut.reactor.http.client
    testRuntimeOnly mnSerde.micronaut.serde.jackson
}
