In your project you can specify exporters that you want to use. The default one is set to "none" value which means by default there are no exporter registered. The available values are defined on the https://github.com/open-telemetry/opentelemetry-java/blob/main/sdk-extensions/autoconfigure/README.md[Open Telemetry Autoconfigure SDK documentation].

For each exporter that you want to use you have to specify it inside configuration, and you have to add required dependency:

- OpenTelemetry Protocol exporter: `otlp`
dependency:opentelemetry-exporter-otlp[scope="implementation", groupId="io.opentelemetry"]
- Logging exporter: `logging`
dependency:opentelemetry-exporter-logging[scope="implementation", groupId="io.opentelemetry"]
- Jaeger exporter: `jaeger`
dependency:opentelemetry-exporter-jaeger[scope="implementation", groupId="io.opentelemetry"]
- Google Cloud Trace: `google_cloud_trace`
dependency:exporter-auto[scope="implementation", groupId="com.google.cloud.opentelemetry"]
- Zipkin exporter: `zipkin`
dependency:opentelemetry-exporter-zipkin[scope="implementation", groupId="io.opentelemetry"]

Example configuration for the Zipkin exporter:

[configuration]
----
otel:
  traces:
    exporter: zipkin
----

Micronaut provides Zipkin exporter that will use Micronaut's HTTP client instead of OKHttp client. That will reduce dependency graph and will make your native executable smaller. To use it add next dependency:

dependency:micronaut-tracing-opentelemetry-zipkin-exporter[scope="implementation", groupId="io.micronaut.tracing"]

To configure Micronaut Zipkin exporter add
[configuration]
----
otel:
  exporter:
    zipkin:
      url: <url-to-zipkin-server>
----

NOTE: Micronaut Zipkin exporter requires `otel.traces.exporter` property not to be defined to avoid conflicts with Open Telemetry default implementation of zipkin exporter.
