In your project you can specify exporters that you want to use. The default one is set to "none" value which means by default there are no exporter registered. The available values are defined on the https://github.com/open-telemetry/opentelemetry-java/blob/main/sdk-extensions/autoconfigure/README.md[Open Telemetry Autoconfigure SDK documentation].

For each exporter that you want to use you have to specify it inside configuration, and you have to add required dependency:

The versionless exporter dependencies below rely on Micronaut dependency management.
If you override the Micronaut Tracing version, import the matching `io.micronaut.tracing:micronaut-tracing-bom` as well so that exporters use the OpenTelemetry version expected by the tracing instrumentation.

- OpenTelemetry Protocol exporter: `otlp`
dependency:opentelemetry-exporter-otlp[scope="implementation", groupId="io.opentelemetry"]
- Logging exporter: `logging`
dependency:opentelemetry-exporter-logging[scope="implementation", groupId="io.opentelemetry"]
- Google Cloud Trace: `google_cloud_trace`
dependency:exporter-auto[scope="implementation", groupId="com.google.cloud.opentelemetry"]
- Zipkin exporter: `zipkin`
dependency:opentelemetry-exporter-zipkin[scope="implementation", groupId="io.opentelemetry"]

OpenTelemetry no longer publishes a Jaeger exporter. Jaeger accepts OTLP, so use the `otlp` exporter to send traces to Jaeger. See <<otlpBackends, OTLP Backends>> for the OTLP settings of Jaeger, Grafana Tempo, Datadog, SkyWalking, Honeycomb and other backends.

For Logback integration details, see the Logback section in this guide.

Example configuration for the Zipkin exporter:

[configuration]
----
otel:
  traces:
    exporter: zipkin
----

WARNING: OpenTelemetry no longer publishes `opentelemetry-exporter-zipkin`; the last release is 1.64.0, which Micronaut Tracing still manages. The `micronaut-tracing-opentelemetry-zipkin-exporter` module below is deprecated and will be removed in a future major release. Prefer the OTLP exporter (`otel.traces.exporter: otlp`): Zipkin can receive OTLP data, for example through an OpenTelemetry Collector.

Micronaut provides Zipkin exporter that will use Micronaut's HTTP client instead of OKHttp client. That will reduce dependency graph and will make your native executable smaller. To use it add next dependency:

dependency:micronaut-tracing-opentelemetry-zipkin-exporter[scope="implementation", groupId="io.micronaut.tracing"]

To configure Micronaut Zipkin exporter add
[configuration]
----
otel:
  exporter:
    zipkin:
      url: <url-to-zipkin-server>
----

NOTE: Micronaut Zipkin exporter requires `otel.traces.exporter` property not to be defined to avoid conflicts with Open Telemetry default implementation of zipkin exporter.
