To enable creating span objects on the every HTTP server request, client request, server response and client response you have to add next depedency:
dependency:micronaut-tracing-opentelemetry-http[scope="implementation", groupId="io.micronaut.tracing"]


== Filtering HTTP spans

It may be useful to exclude health-checks and other HTTP requests to your service.
This can be achieved by adding a list of regular expression patterns to your configuration:

.Filtering HTTP request spans
[configuration]
----
otel:
  exclusions:
    - /health
    - /env/.*
----

== Add HTTP Headers into request spans

If you want you can add additional Http Headers inside your span objects. You can specify different headers for client request, client response, server request and server response.

.Adding HTTP Headers into request spans
[configuration]
----
otel:
  http:
    client:
      request-headers:
        - X-From-Client-Request
      response-headers:
        - X-From-Client-Response
    server:
      request-headers:
        - X-From-Server-Request
      response-headers:
        - X-From-Server-Response
----

== Customizing HTTP instrumentation

HTTP client and server OpenTelemetry `Instrumenter` builders can be customized by defining beans with the appropriate qualifier:

* ann:tracing.opentelemetry.instrument.http.client.MicronautHttpClientTelemetryFactory.Client[] for HTTP client instrumentation.
* ann:tracing.opentelemetry.instrument.http.server.MicronautHttpServerTelemetryFactory.Server[] for HTTP server instrumentation.

Qualified beans of type `SpanNameExtractor`, `SpanStatusExtractor`, `ErrorCauseExtractor`, `AttributesExtractor`, `ContextCustomizer`, `OperationMetrics`, `OperationListener`, and `SpanLinksExtractor` are applied when the Micronaut HTTP instrumenters are built. `SpanNameExtractor`, `SpanStatusExtractor`, and `ErrorCauseExtractor` are single collaborators and do not compose; if one already exists, replace it with ann:context.annotation.Replaces[]. `AttributesExtractor`, `ContextCustomizer`, `OperationMetrics`, `OperationListener`, and `SpanLinksExtractor` beans are additive contributors.

NOTE: Custom extractors, customizers, metrics, listeners, and span link extractors can add request, response, exception, and application data to telemetry. Redact secrets such as authorization headers, cookies, API keys, tokens, and personally identifiable information before exporting telemetry.
