== Add Kafka Message Headers into request spans

To enable creating span objects on the every Kafka message. You have to add next depedency:
dependency:micronaut-tracing-opentelemetry-kafka[scope="implementation", groupId="io.micronaut.tracing"]

.Adding Kafka Message Headers into request spans
[configuration]
----
otel:
  instrumentation:
    kafka:
      wrapper: true
      headers-as-lists: false
      attribute-with-prefix: true
      attribute-prefix: myPrefix
      captured-headers: # list of headers wich need to send as span attributes
        - myHeader1
        - myHeader2
      included-topics:
        - topic1
        - topic2
      excluded-topics:
        - topic1
        - topic2
----

- `wrapper` - if "true" tracing will be tracing will be done using object proxies over cosumers and producers. If wrappers are disabled, then tracing can be done through kafka listener
- If you want to set headers as lists, set `headers-as-lists` to `true`.
- `attribute-with-prefix` - add or not prefix to span attribute names (default: false)
- `attribute-prefix` - custom prefix for span attributes (header names). Default: *messaging.header.*
- `captured-headers` is the list of headers to add as span attributes. By default, all headers are added as span attributes. To set no headers as span attributes, specify `null` or an empty string.
- `included-topics` - list of topics to trace
- `excluded-topics` - list of topics to exclude of tracing

NOTE: You can't use `included-topics` and `excluded-topics` properties together. Need to set included OR excluded topics.
