To enable creating span objects on the every Kafka message, add the following depedency:
dependency:micronaut-tracing-opentelemetry-kafka[scope="implementation", groupId="io.micronaut.tracing"]

== Add Kafka Message Headers into request spans

The way Kafka Message Headers are added inside your span objects may be configured as follows: 

.Adding Kafka Message Headers into request spans
[configuration]
----
otel:
  instrumentation:
    kafka:
      wrapper: true
      headers-as-lists: false
      attribute-with-prefix: true
      attribute-prefix: myPrefix
      captured-headers: # list of headers which need to send as span attributes
        - myHeader1
        - myHeader2
      included-topics:
        - topic1
        - topic2
      excluded-topics:
        - topic1
        - topic2
----

- `wrapper` - if "true" tracing will be done using object proxies over consumers and producers. If wrappers are disabled, then tracing can be done through a kafka listener instead.
- If you want to set headers as lists, set `headers-as-lists` to `true`.
- `attribute-with-prefix` - whether to add a prefix to span attribute names (default: false)
- `attribute-prefix` - custom prefix for span attributes (header names). Default: *messaging.header.*
- `captured-headers` is the list of headers to add as span attributes. By default, all headers are added as span attributes. To set no headers as span attributes, specify `null` or an empty string.
- `included-topics` - list of topics to trace
- `excluded-topics` - list of topics to exclude from tracing

NOTE: You can't use `included-topics` and `excluded-topics` properties together as they are mutually exclusive - choose one or the other.
